print('-' * 30)
print('Bem vindo a locadora Hot Uils!')
print('-' * 30)
print('')
print('Descubra quanto irá pagar ao fim do aluguel.')
print('')
km = int(input('Quantos km você rodou? '))
dias = float(input('Por quantos dias alugou? '))
pagar = (dias * 60) + (km * 0.15)
print('O valor total do alguem fica em R${:.2f}'.format(pagar))